### ISSUE TITLE
BBOX is always written for Feature and FeatureCollection objects

### ISSUE THREAD

**Issue by DGuidi** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#100]
behaviour verified with `GeoJSON4STJ` see [Spatialite Issue 8](https://github.com/NetTopologySuite/NetTopologySuite.IO.SpatiaLite/issues/8#issuecomment-1063486404)

**Comment by MLongz** [comment]
I had the same issue and found out you can pass `options.JsonSerializerOptions.IgnoreNullValues = true;` to ignore bbox since in the internal method they skip adding `bbox` if the boundingbox value is null and IgnoreNullValues is true.

```
internal static void WriteBBox(Utf8JsonWriter writer, Envelope value, JsonSerializerOptions options, Geometry geometry)
{
    // if we don't want to write "null" bounding boxes, bail out.
    if ((value == null || value.IsNull) && options.IgnoreNullValues)
        return;
```

**Comment by DGuidi** [comment]
@MLongz howewer, this works only for `null` bbox, valid bboxes are written
