### ISSUE TITLE
Geometry modified bug in GeoJsonWriter()

### ISSUE THREAD

**Issue by MaroonMike1** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#114]
I uncovered a bug in the latest GeoJsonWriter().  After weeks of debugging code, the issues all resolved by rolling back from v3 to v 2.0.4

Somehow, the dimensions of Feature.Geometry are being changed in the GeoJsonWriter() process. In my process, this resulted in malformed geometries that later triggered a TopologyException when performing an intersection.   

I am attaching a geojson for one of the geometries that always changed during the geojson write.  

In case you need it for reference, my code for writing is pretty simple:

**FeatureCollection fc = new FeatureCollection();
foreach (int id in Featurecoll.Keys)   //Featurecoll is a Dictionary of <int, Feature> 
{               
    fc.Add(Featurecoll[id]);                           
}
GeoJsonWriter jsonwtr = new GeoJsonWriter();
string filecontents = jsonwtr.Write(fc);
File.WriteAllText(@sPath, filecontents)**;

Please let me know if you need more information to replicate the bug.   Thanks.

[sample.zip](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/files/10290314/sample.zip)

**Comment by alex2512** [comment]
I fixed the same bug in https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/pull/130

**Comment by FObermaier** [comment]
> Please let me know if you need more information to replicate the bug. Thanks.

1. The `FeatureCollection` in sample.json has already been written using `GeoJsonWriter`, e.g. the geometries are already changed?
2. It takes 2 geometries for intersection operation. What does the other look like?
3. The intersection operation does not fail when the geometry has not been changed?
