### ISSUE TITLE
Missing assembly reference at GeoJsonConverterFactory

### ISSUE THREAD

**Issue by SheldonHage** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#115]
When I try to follow the example code found in readme.md for installing GeoJSON I am unable to reference GeoJsonConverterFactory.

I added `NetTopologySuite.IO.GeoJSON` nuget package to my project and I added `using NetTopologySuite.IO.Converters` to my Startup.cs file.

I receive the following error message:
`The type or namespace name 'GeoJsonConverterFactory' does not exist in the namespace 'NetTopologySuite.IO.Converters' (are you missing an assembly reference?)`

Perhaps I am missing an additional prerequisite nuget package but I find no docs on the matter.  I do not see a `GeoJsonConverterFactory.cs` file in `Converters` repo folder.  Is this expected?

**Comment by FObermaier** [comment]
The `GeoJsonConverFactory` is part of the `NetTopologySuite.IO.GeoJSON4STJ` package.

**Comment by DGuidi** [comment]
yep, [exactly](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/8b2f9e5df585a8bf26e6aab7085f5b46a9f936f9/src/NetTopologySuite.IO.GeoJSON4STJ/Converters/GeoJsonConverterFactory.cs)
