### ISSUE TITLE
Not able to serialize using library GeoJSON4STJ

### ISSUE THREAD

**Issue by mhosman** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#123]
With GeoJSON4STJ, using System.Text.Json, and trying to serialize an object with Geometry attribute, I get:

`".NET number values such as positive and negative infinity cannot be written as valid JSON. To make it work when using 'JsonSerializer', consider specifying 'JsonNumberHandling.AllowNamedFloatingPointLiterals' (see https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonnumberhandling)."`

I already added:

`options.JsonSerializerOptions.Converters.Add(new NetTopologySuite.IO.Converters.GeoJsonConverterFactory());`

And even:

`options.JsonSerializerOptions.NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals`

But is not working...

**Comment by FObermaier** [comment]
Could you set up a unit test that demonstrates the issue?

**Comment by mhosman** [comment]
Closing. This is related to: https://github.com/dotnet/efcore/issues/28811
