### ISSUE TITLE
serializer produces noncompliant GeoJSON feature when geometry or properties is null

### ISSUE THREAD

**Issue by jjanuszkiewicz** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#128]
When serializing a feature with a `null` geometry or attributes, and when `JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull` (for STJ) or `NullValueHandling == NullValueHandling.Ignore` (for Newtonsoft.Json), the written feature JSON doesn't have the `geometry` and/or `properties` members, which is not valid as per [RFC 7946](https://datatracker.ietf.org/doc/rfc7946/) section 3.2. Feature Object:

>  - A Feature object has a member with the name "geometry".  The value
>      of the geometry member SHALL be either a Geometry object as
>      defined above or, in the case that the Feature is unlocated, a
>      JSON null value.
>
>  -  A Feature object has a member with the name "properties".  The
>      value of the properties member is an object (any JSON object or a
>      JSON null value).

I'll create a PR with a proposed fix. I will only change the writing code - I think it's OK to keep the deserializer as-is (it allows for missing `geometry` and `properties` in input and treats them as `null`).

**Comment by FObermaier** [comment]
Fixed with #129
