### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#131]
Is it possible to release a new official version?
I'm using 3.1.0-pre.193970619
from https://www.myget.org/F/nettopologysuite/api/v3/index.json
Which is currently down :-(

**Comment by HarelM** [comment]
I now see that `myget` returned to work, but `dotnet restore` fails in my CI.
It is possible that the packages that were there are no longer there?

**Comment by xivk** [comment]
There are only 2 commits since the latest release I think. As far as I can see releasing is as easy are merging develop into master, perhaps a pull request has more success 🙂

**Comment by HarelM** [comment]
I'll be happy to send a PR, but I'm not sure what's needed.
I don't have write permissions in this repo as far as I know.
The main item that was not released was the writable `IAttributeTable` for STJ.
I'm currently using it in my production environment, so I think it's safe to release it.

**Comment by jjanuszkiewicz** [comment]
Since #125 and #129 were merged, does this warrant a new version now? I'd like to use an official package in my projects.

I've tried to create a develop => master PR, but have no permissions (Pull request creation failed. Validation failed: must be a collaborator).

**Comment by HarelM** [comment]
@airbreather @FObermaier Any chance to merge dev to master and create a new version?

**Comment by FObermaier** [comment]
We attempt to sort out #130 the. we'll release.

**Comment by HarelM** [comment]
@FObermaier Thanks for the info and fast response!
There's also this problem if you are looking into the coordinates sequence stuff:
https://github.com/NetTopologySuite/NetTopologySuite/issues/356#issuecomment-1606106428
I ended up copying the data unfortunately...
But a new version is welcome anytime :-)

**Comment by airbreather** [comment]
> We attempt to sort out #130 the. we'll release.

For my part, if we don't hear back on that one in a timely manner, I think we should:
1. Take the change as-is, with the **same** change to [the equivalent on the STJ side](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/develop/src/NetTopologySuite.IO.GeoJSON4STJ/Converters/StjGeometryConverter.Coordinates.cs#L24C21-L24C59)
2. Close #130 but ask for more specific details on #114

**Comment by jf2020** [comment]
If you are releasing a new version can you also please bump the Newtonsoft.Json dependency to 13.0.1?   This would address this advisory issue [Improper Handling of Exceptional Conditions in Newtonsoft.Json](https://github.com/advisories/GHSA-5crp-9r3c-p9vr)  that shows in our dependency scanner. Many thanks!

**Comment by FObermaier** [comment]
At last.

**Comment by HarelM** [comment]
THANKS!! Keep up the good work!

**Comment by jjanuszkiewicz** [comment]
Fantastic, thank you!
