### ISSUE TITLE
Wrong SRID after deserializing

### ISSUE THREAD

**Issue by jochenjonc** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#16]
Hi,

After deserializing a geojson object the SRID is 0 by default. But according to the [geojson specs]( https://tools.ietf.org/html/rfc7946) the 
coordinate reference system is WGS 84, meaning SRID 4326.

Shouldn't it be more logic and correct if the default GeometryFactory used by the GeoJsonSerializer would have 4326 as SRID.

https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/c661b78167bcf629da6e1c9b912db20542656109/NetTopologySuite.IO.GeoJSON/GeoJsonSerializer.cs#L37

So instead of `GeometryFactory.Default` use `new GeometryFactory(new PrecisionModel(), 4326)`.

Regards,

Jochen

**Comment by FObermaier** [comment]
Changed behaviour with c7a07e5

**Comment by jochenjonc** [comment]
I just pulled the newest release from NuGet but the problem still exists.

In the GeoJsonSerializer, GeometryFactory.Default is used instead of the new Wgs84Factory.

https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/0daa79ec7de3c0089656d02feca648517ec70fc5/NetTopologySuite.IO.GeoJSON/GeoJsonSerializer.cs#L37

**Comment by FObermaier** [comment]
Fixed with 4d8d506e2e5e847bd724c70c580635c5670ec917
