### ISSUE TITLE
how to use it  with JSON.net

### ISSUE THREAD

**Issue by asypost** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#17]
Is there a guide or something on how to use it with JSON.net.I tried add a JsonConverter attribute,but it not work as expected.

**Comment by FObermaier** [comment]
ATM this package is tied to `NewtonSoft.Json`

**Comment by airbreather** [comment]
Json.NET == `Newtonsoft.Json`

This is the second issue (see also #5) asking for more documentation on how to actually use this package.  I've never personally used it in any serious way (there appear to be several different ways to use it), so I don't think I'm a good candidate for writing it.

**Comment by asypost** [comment]
This is my case, I have a model with a MultiLineString property defined like below:
`[JsonConverter(typeof(GeometryConverter))]
 public MultiLineString Geom { get; set; }`

The generated JSON is:
`"Geom":{"type":"MultiLineString","coordinates":[[{"X":117.19685575357698,"Y":31.668701341760084,"Z":"NaN"},....]]}`
That is not GeoJSON.
Did I use it in a wrong way?

**Comment by FObermaier** [comment]
Can this be closed?

**Comment by FObermaier** [comment]
Update: Changing the attribute to `MyModelItem.Geom` to
```C#
[Newtonsoft.Json.JsonProperty(PropertyName = "geometry", ItemConverterType = typeof(NetTopologySuite.IO.Converters.GeometryConverter))]
```
gives a valid geojson:
```
{"geometry":{"type":"MultiLineString","coordinates":[[[10.0,10.0],[20.0,10.0]],[[10.0,11.0],[20.0,11.0]],[[10.0,12.0],[20.0,12.0]]]}}
```

**Comment by asypost** [comment]
@FObermaier Thanks for your help!

**Comment by aschaible** [comment]
Hello - and my apologies for posting in a closed issue but I wasn't sure which place would be best.  I followed the wiki, and this is not working for me in dotnet core 3.  I have done:

`.AddNewtonsoftJson(options =>
{
	options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
	options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
	options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
	foreach (var converter in GeoJsonSerializer.Create(new GeometryFactory(new PrecisionModel(), 4326)).Converters)
	{
		options.SerializerSettings.Converters.Add(converter);
}}).SetCompatibilityVersion(CompatibilityVersion.Version_3_0);`


And also decorated my model property with: 
`[Newtonsoft.Json.JsonProperty(PropertyName = "geometry", ItemConverterType = typeof(NetTopologySuite.IO.Converters.GeometryConverter))]` but it is generating a recursive/infinite loop of json that doesn't valid geojson
