### ISSUE TITLE
GeoJsonWriter.Write fails with empty FeatureCollection

### ISSUE THREAD

**Issue by robicide** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#19]
When calling `Write(FeatureCollection featureCollection)` with an empty FeatureCollection, an ArgumentOutOfRangeException is thrown.

    var writer = new GeoJsonWriter();
    var json = writer.Write(new FeatureCollection());

This throws the following:
`System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than 
the size of the collection.`
`Parameter name: index`

**Comment by FObermaier** [comment]
Fixed with c7a07e518a9aba925fb70690dcb41ca7808c2872
