### ISSUE TITLE
What is the purpose of this repo?

### ISSUE THREAD

**Issue by stijnherreman** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#2]
Is this repo meant to replace https://github.com/NetTopologySuite/NetTopologySuite/tree/develop/NetTopologySuite.IO/NetTopologySuite.IO.GeoJSON ?
If so, how come changes were done in the original repo, but not here?

Which repo is https://www.nuget.org/packages/NetTopologySuite.IO.GeoJSON/ built from?

**Comment by xivk** [comment]
The idea is that everything moves except for the core NTS code that's in sync with JTS to seperate repos. At the moment the packages are still built from the main repo but that's going to change. When we do this we can release packages (stables) more quickly and update faster on all projects but the NTS core.

If you have issues please log them here, I'll see about continuing the work of splitting up the main repo soon.

**Comment by stijnherreman** [comment]
OK, thank you for the info :)
