### ISSUE TITLE
Update to latest NTS Core

### ISSUE THREAD

**Issue by DarinMacRae** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#22]
There are some important bug fixes in the latest 1.15.2 version of the NTS Core package. Can you please ship a new version that references that one?

**Comment by FObermaier** [comment]
Adding explicit reference to NetTopologySuite.Core package v1.15.2 should resolve your issue.

**Comment by DarinMacRae** [comment]
It does not but it's due to a problem with binding redirects in Azure Functions v1. This request was made with the hope that updating to the latest would help me work around that issue but in the meantime I've began upgrading to AF v2 which does not have the issue.
