### ISSUE TITLE
GeoJsonSerializer.Deserialize<Coordinate> return null

### ISSUE THREAD

**Issue by sergei66666** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#31]
Hello!
I try write Coordinate to json and than read it back to object.

```
var geoSerializer = GeoJsonSerializer.CreateDefault();

var c1 = new Coordinate(1, 2);
var sb = new StringBuilder();
geoSerializer.Serialize(new JsonTextWriter(new StringWriter(sb)), c1);
var json = sb.ToString(); // it is equal to "[1.0,2.0]"

var c2 = geoSerializer.Deserialize<Coordinate>(new JsonTextReader(new StringReader(json)));
```

As we can see json is correct, but after `Deserialize` I got null.

I assume, that CoordinateConverter which sit inside GeoJsonSerializer should do both write and read conversion, but it doesn't. It is issue or correct behavior?

I use 1.15.3 version of NetTopologySuite and NetTopologySuite.IO.GeoJSON.

**Comment by sl-tomtom** [comment]
Hello, 

Yes I think it's bug.

![image](https://user-images.githubusercontent.com/31064278/61941509-ec3f3a80-af97-11e9-8226-7c473a4966ee.png)

the "if" condition should be false

**Comment by DGuidi** [comment]
not sure, but GeoJsonSerializer expects something like a complete GeoJSON, not a "chunk" (like the simple coordinate array you're passing) so I suspect you broke almost everything changing the if clause

**Comment by sergei66666** [comment]
GeoJsonSerializer consists of several converters. One of them is CoordinateConverter and I assume it contains bug.

**Comment by DGuidi** [comment]
@sergei66666 nope, I think. 

You're calling GeoJsonSerializer passing a coordinate, not a geometry object (see [specs](https://tools.ietf.org/html/rfc7946)).
So to me code is broken because should throw an exception here
```
geoSerializer.Serialize(new JsonTextWriter(new StringWriter(sb)), c1);
```
My2Cents.

**Comment by airbreather** [comment]
>> not sure, but GeoJsonSerializer expects something like a complete GeoJSON, not a "chunk" (like the simple coordinate array you're passing) so I suspect you broke almost everything changing the if clause
>
> GeoJsonSerializer consists of several converters. One of them is CoordinateConverter and I assume it contains bug.

I agree that this is a bug.

If we're not supporting (de/)serializing individual `Coordinate` objects, then we should not be advertising a `JsonConverter` implementation for which `CanConvert(typeof(Coordinate))` returns `true`.
