### ISSUE TITLE
GeoJsonReader to support Stream

### ISSUE THREAD

**Issue by m1dst** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#32]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Currently the only input the Read method supports is string.  It would be great if this method also supported a stream.  This would be useful for large datasets and memory management.

**Comment by airbreather** [comment]
Agreed, probably should accept an instance of `JsonReader` for maximum flexibility, since that's what I understand JSON.NET builds everything on top of.

**Comment by m1dst** [comment]
Sounds good to me.

**Comment by stijnherreman** [comment]
@airbreather I also need this and I'm ready to create a PR, but it would conflict with the wip/v2 branch because of the renames. Would you like me to send it now or should I wait until wip/v2 is merged into master?

**Comment by airbreather** [comment]
> @airbreather I also need this and I'm ready to create a PR, but it would conflict with the wip/v2 branch because of the renames. Would you like me to send it now or should I wait until wip/v2 is merged into master?

I just did e582f9a on the wip/v2 branch which should be good enough once v2 is settled.
