### ISSUE TITLE
Release a version compatible with .NET Core 3.0 preview 7

### ISSUE THREAD

**Issue by mcartoixa** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#33]
The [latest version of .NET Core 3.0](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-7/), and more specifically [Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite/3.0.0-preview7.19362.6) now depends on the latest _NetTopologySuite 2.0.0-pre001_ package. This version no longer depends on GeoAPI.NET: geometry types are now an integral part of the _NetTopologySuite_ API.
This library, which acts on GeoAPI.NET instances, can no longer work in this environment. And so it seems to me that it needs some love right now.

I might be able to contribute on this one. I would probably need quite some guidance though.

**Comment by mhosman** [comment]
Same issue here!

**Comment by airbreather** [comment]
NetTopologySuite/NetTopologySuite.Features#8 is the latest on this right now.

**Comment by airbreather** [comment]
Branch [`wip/v2`](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/tree/wip/v2) is basically what we need for this, once NetTopologySuite.Features is updated.

**Comment by mhosman** [comment]
Sorry, but I did not understand. `NetTopologySuite.Features` is gonna replace `NetTopologySuite.IO.GeoJSON`?

**Comment by mhosman** [comment]
Could you please release a preview version of this too into NuGet? Thank you very much!

**Comment by tinchoel10** [comment]
I have also the same issue. There is any NuGet package in preview, in order to use this with .NET Core 3.0 Preview 7? Thanks!

**Comment by mhosman** [comment]
.NET Core 3.0 Preview 8 was released today. There is no way to release a preview package to achieve this?

**Comment by martinrocanova** [comment]
Any news??? Same issue here!!

**Comment by airbreather** [comment]
2.0.0-pre001 is on NuGet now.
