### ISSUE TITLE
Convert GeoJSON to PBF tiles

### ISSUE THREAD

**Issue by livebird** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#39]
I need to convert the GeoJSON to PBF vector tiles. Is there any way to do that?

**Comment by donnyv** [comment]
You can use [tippecanoe](https://github.com/mapbox/tippecanoe) or [ogr2ogr](https://gdal.org/drivers/vector/mvt.html). Export to directory will create pbf vector tiles.

**Comment by xivk** [comment]
I started on something basic here:

https://github.com/anyways-open/NetTopologySuite.IO.VectorTiles

But I would also use one of the mentioned tools. My work is far from useable for general purposes.

**Comment by donnyv** [comment]
> I started on something basic here:
> 
> https://github.com/anyways-open/NetTopologySuite.IO.VectorTiles
> 
> But I would also use one of the mentioned tools. My work is far from useable for general purposes.

@xivk Ooooooh snap! This is awesome! Are you shooting for spec 2 compliant?

**Comment by xivk** [comment]
Well we plan to use it with mapbox gl js so anything that needs we will build. I am aiming for support for relatively small datasets or chuncks of data.

I don' t have a roadmap or eta for this package.

**Comment by donnyv** [comment]
I would think once you cover the spec. The size of the data wouldn't matter.

**Comment by HarelM** [comment]
There's also this format which is not tiled based:
https://github.com/mapbox/geobuf
Wasn't sure where to write this down as there's probably a need to another NTS project/repo for this.
@xivk what's the status on your project? Can it be used to convert GeoJson to MVT?

**Comment by FObermaier** [comment]
Use functionality in `NetTopologySuite.IO.VectorTiles`
