### ISSUE TITLE
Compatibility with Asp.Net 3.0 Json Serialization changes

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#42]
It appears that Microsoft has decided to create its own Json library focused on perfomance.
Can be seen here:
https://github.com/dotnet/announcements/issues/90
https://github.com/aspnet/Announcements/issues/325
I know that Json.Net is still supported but I was wondering if the new Json will be supported by this library?
In any case, the [wiki page](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/wiki/HowTo-...) should be updated since there were breaking changes introduced in 3.0.
If I manage to make it work using this [SO question](https://stackoverflow.com/questions/55666826/where-did-imvcbuilder-addjsonoptions-go-in-net-core-3-0) I'll update the wiki.

**Comment by airbreather** [comment]
> I was wondering if the new Json will be supported by this library?

I would expect that we would make a new package for integration with `System.Text.Json`, as I don't think someone would want to add a dependency on `Newtonsoft.Json` just to get this integration.

It would probably make sense to keep it in the same repository though.

**Comment by Buzzology** [comment]
@HarelM's suggestion ended up working for me. This is the relevant section in my startup.cs in case anyone needs it:

`
services.AddControllers(options =>
{
    // Prevent the following exception: 'This method does not support GeometryCollection arguments'
    // See: https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/585
    options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Point)));
    options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Coordinate)));
    options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(LineString)));
    options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(MultiLineString)));
})
.AddNewtonsoftJson(options =>
{
    foreach (var converter in NetTopologySuite.IO.GeoJsonSerializer.Create(new GeometryFactory(new PrecisionModel(), 4326)).Converters)
    {
        options.SerializerSettings.Converters.Add(converter);
    }
})
.SetCompatibilityVersion(CompatibilityVersion.Version_3_0);
`

+1 to what @airbreather has said though, would ideally like to drop newtonsoft when possible. 

Thanks!

**Comment by HarelM** [comment]
Thanks @Buzzology ! Can you please add the relevant instructions to the wiki page, including the relevant packages you added + minimal code to make it work?

**Comment by HarelM** [comment]
@FObermaier @airbreather Can you please add this to the wiki, I don't have permissions to edit it.
Needs the following package added to support newtonsoft json:
`<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0" />`
And the following code:
```cs
services.AddControllers(options => { 
// Prevent the following exception: 'This method does not     support GeometryCollection arguments' 
// See: https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/585 
    options.ModelMetadataDetailsProviders.Add(new     SuppressChildValidationMetadataProvider(typeof(Point))); 
    options.ModelMetadataDetailsProviders.Add(new uppressChildValidationMetadataProvider(typeof(Coordinate))); 
    options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(LineString))); 
    options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(MultiLineString))); 
}).AddNewtonsoftJson(options => { 
    foreach (var converter in NetTopologySuite.IO.GeoJsonSerializer.Create(new GeometryFactory(new PrecisionModel(), 4326)).Converters) { 
        options.SerializerSettings.Converters.Add(converter); 
    } 
}).SetCompatibilityVersion(CompatibilityVersion.Version_3_0);
```

Can also be seen here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/Startup.cs#L66L76

**Comment by FObermaier** [comment]
@HarelM could you please check if the updated wiki page is correct? I'll see what I can do about the editing rights on the wiki.

**Comment by HarelM** [comment]
Looks good, Thanks!

**Comment by FObermaier** [comment]
> I would expect that we would make a new package for integration with System.Text.Json, as I don't think someone would want to add a dependency on Newtonsoft.Json just to get this integration.
> 
> It would probably make sense to keep it in the same repository though.

I 2nd that. It does not mean that it can't have its own nuget package. I'll create a new issue for this, as this one seems to be resolved.

**Comment by HarelM** [comment]
Well, this was the intentions of this issue, originally, but it side tracked a bit.
A new issue wouldn't hurt though...
