### ISSUE TITLE
How serialize FeatureCollection with Multilinestring and Z coordinate?

### ISSUE THREAD

**Issue by flankermain** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#53]
I created FeatureCollection with geometry Multilinestring and wrote her to JSON string. In geometry, I have Z coordinate.

GeoJsonWriter writer = new GeoJsonWriter();
var geoJson = writer.Write(mycollection);

It's ok. I get string GeoJSON, but without Z coordinate.
" "coordinates": [
    [
      [
        1263.1974032828948,
        11930.429698849097
      ],
      [
        1264.6275812591848,
        11917.549948748201
      ],
      [
        1368.966530531652,
        11924.469217129983
      ],"

Why and how to add Z?

**Comment by xfischer** [comment]
Hi ! I have the same issue here, is there a workaround or some hints for a PR ?
Thanks
