### ISSUE TITLE
Trouble serializing valid GeoJSON with "properties" field

### ISSUE THREAD

**Issue by oshawaConnectionJBA** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#64]
Hello, I am having a problem with the final GeoJSON structure after serializing an object.
Psuedocode for the model:

```csharp
public class Country
{
     public string ID {get; set;}
     public int Name{get; set;}
     public Geometry Geometry {get; set;}
}        
```

Psuedo-code for the controller:
```csharp
public IActionResult ExampleGeoJSON()
{
    
    Country country = countriesRepo.GetCountryFromDatabaseByID("AA");
   //
    
    string geoJson;
    var serializer = GeoJsonSerializer.Create();
    using (var stringWriter = new StringWriter())
    using (var jsonWriter = new JsonTextWriter(stringWriter))
    {
        serializer.Serialize(jsonWriter, country);
        geoJson = stringWriter.ToString();
    }
    
    return this.Content(geoJson, "application/json");
}
```
The returned JSON looks like this:
```json
{"ID":"1","Name":"AA","Geometry":{"type":"Point","coordinates":[1.2,1.2]}}
```
As we can see, the geometry is coming through perfectly and as expected, but 

1. There is no "type" field for the geoJSON.
2. there is no "properties" field. In order to be a valid GeoJSON, the json should be structured like this:
```json
{"type": "Feature","Geometry":{"type":"Point","coordinates":[1.2,1.2]}, "Properties":{"ID":"1","Name":"AA"}}
```
Is this functioning as intended, is there something I've missed/ an option for this? Or is this something I have to write myself?

**Comment by airbreather** [comment]
> `{"type": "Feature","Geometry":{"type":"Point","coordinates":[1.2,1.2]}, "Properties":{"ID":"1","Name":"AA"}}`

GeoJSON "Features" need to be instances of the `IFeature` interface.

Try something more like this:
```csharp
    Country country = countriesRepo.GetCountryFromDatabaseByID("AA");
    var countryFeature = new NetTopologySuite.Features.Feature
    {
        Geometry = country.Geometry,
        Attributes = new new NetTopologySuite.Features.AttributesTable
        {
            { "ID", country.ID },
            { "Name", country.Name },
        },
    };
   //
    
    string geoJson;
    var serializer = GeoJsonSerializer.Create();
    using (var stringWriter = new StringWriter())
    using (var jsonWriter = new JsonTextWriter(stringWriter))
    {
        serializer.Serialize(jsonWriter, countryFeature);
        geoJson = stringWriter.ToString();
    }
```

**Comment by oshawaConnectionJBA** [comment]
Thanks so much for your quick response, your answer worked perfectly! 
Marking issue as closed. Are there any docs that cover this?

**Comment by airbreather** [comment]
> Are there any docs that cover this?

Documentation is rather scant at the moment.  We need to do a better job at this.
