### ISSUE TITLE
GeoJSON parser fails to parse properties

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#7]
_From @dmytro-gokun on March 27, 2018 14:52_

Hi,

i have this piece of GeoJSON:

```
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      12.5851472,
      55.68323837
    ]
  },
  "crs": {
    "type": "name",
    "properties": {
      "name": "EPSG:4326"
    }
  },
  "properties": {
    "id": "0a3f507a-b2e6-32b8-e044-0003ba298018",
    "status": 1,
    "vejkode": "4112",
    "vejnavn": "Landgreven",
    "adresseringsvejnavn": "Landgreven",
    "husnr": "10",
    "supplerendebynavn": null,
    "postnr": "1301",
    "postnrnavn": "København K",
    "kommunekode": "0101"
  }
}
```

I use this code to parse it:

```C#
var feature = new GeoJsonReader().Read<Feature>(json);
```

The resulting "feature" object contains just 1 element in it's "Attributes" property. One named "name" with value of "EPSG:4326". Instead, I expect it to contain "id", "status", "vejkode" and so on. Obviously, the parser is fooled by "properties" nested inside of "crs".

Thanks in advance,
Dmytro.

_Copied from original issue: NetTopologySuite/NetTopologySuite#224_

**Comment by FObermaier** [comment]
Cannot confirm (see 64474ebb6760d4ac60383f7d3cc842f53e5c0a89).
Might have been fixed with 4b28201f6ae3f4dfd0ab225decd48c47c7d80410
