### ISSUE TITLE
annoying trace of  "Factory with SRID of unsupported coordinate reference system. "

### ISSUE THREAD

**Issue by watanabelikewelltech** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#75]
I am using GeoJsonWriter with geometry of srid 3857.
GeoJsonWriter works fine,but Write method shows "Factory with SRID of unsupported coordinate reference system.".

**Comment by FObermaier** [comment]
Fixed with 8f6534aff5cfe1795abdd04ac6cde2fcc67a53b9
