### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tunnelpuzzle** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#78]
What is the license for this project? I didn't see one listed. Thank you!

**Comment by FObermaier** [comment]
There are actually 2 projects in this repository:
Project | License
--- | ---
`NetTopologySuite.IO.GeoJSON` | LGPL 2.1 or later
`NetTopologySuite.IO.GeoJSON4STJ` | BSD 3

I'll check if we can apply a more permissive license to `NetTopologySuite.IO.GeoJSON`

**Comment by airbreather** [comment]
> I'll check if we can apply a more permissive license to `NetTopologySuite.IO.GeoJSON`

I came up with a list of external contributions, prior to us requiring a CLA, in NetTopologySuite/NetTopologySuite#238

**Comment by FObermaier** [comment]
The initial code was partly ported from [GeoJSON.Net](/GeoJSON-Net/GeoJSON.Net)
It has an MIT license so from that side we should be able to change the license.
Did we split the projects before we started requiring a CLA?

**Comment by airbreather** [comment]
> Did we split the projects before we started requiring a CLA?

Yes, and also it looks like the CLA checker missed some PRs early on:

- #11, but that one's fine because the PR was from someone who definitely did sign the CLA
- #15 is a very very small fix (the only significant part is a new test)

**Comment by FObermaier** [comment]
We have consent from #15 contributor, so let us do it. Can we use BSD-3?

**Comment by airbreather** [comment]
> We have consent from #15 contributor, so let us do it. Can we use BSD-3?

Yes, let's.

> The initial code was partly ported from [GeoJSON.Net](/GeoJSON-Net/GeoJSON.Net)
> It has an MIT license so from that side we should be able to change the license.

Regardless of what we do with our own license, if substantial amounts of our code was ported this way, then I believe that we need to include some language in our own publications and repository indicating as much.

If it was done prior to GeoJSON-Net/GeoJSON.Net@360ae6b, then we should follow the rules of their own BSD3 license, otherwise we should follow the rules of their own MIT license.

**Comment by FObermaier** [comment]
The initial commit for [NTS.IO.GeoJSON](/NetTopologySuite/NetTopologySuite/commit/034d6ecee9b33b1bf34861077cc125ed2bca74c0) was from 2011/10/26, so we can stick with BSD-3

> Regardless of what we do with our own license, if substantial amounts of our code was ported this way, then I believe that we need to include some language in our own publications and repository indicating as much.

Yes!
