### ISSUE TITLE
Feature id not serialized correctly

### ISSUE THREAD

**Issue by naninue** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#79]
### Description
I have experience a problem with serializing Feature objects containing IDs. 
I'm new to this library, so I apologize in advance, if this is a mistake on my part. 

I am aware that an id is placed in the attributes property of a Feature object
When serialized to GeoJSON, ids should be placed in the root of the Feature objects. 
This is also the case when using the following code: 
```
var serializer = GeoJsonSerializer.Create();
using var stringWriter = new StringWriter();
using var jsonWriter = new JsonTextWriter(stringWriter);
serializer.Serialize(jsonWriter, feature);
var geoJsonStr = stringWriter.ToString();
```

However, when a Feature object is returned from an API Controller action, the id is incorrectly placed under properties in the response payload:
```
{
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [0, 0]
    },
    "properties": {
        "name": "Test feature",
        "id": 1
    }
}
```

### Steps to Reproduce
.NET Core 3.1 web application with `GeoJsonConverterFactory `added to `JsonSerializerOptions `

Controller action:
```
[HttpGet]
public Feature GetFeature()
{
    var feature = new Feature {
        Geometry = new Point(0, 0),
        Attributes = new AttributesTable(new Dictionary<string, object> {
            { "name", "Test feature" },
            { "id", 1 }
        })
    };
    return feature;
}
```
### System Configuration
- .NET version: .NET Core 3.1
- "NetTopologySuite" Version: 2.1.0
- "NetTopologySuite.IO.GeoJSON" Version: 2.0.4
- "NetTopologySuite.IO.GeoJSON4STJ" Version: 2.1.1

**Comment by airbreather** [comment]
`GeoJsonConverterFactory` will write out the "id" for a Feature if you set a special attribute in the feature's `Attributes` table.

By default, the special attribute that it looks for is "[`_NetTopologySuite_id`](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/106db44029ca67e207e4c88400537f49c005aa7c/src/NetTopologySuite.IO.GeoJSON4STJ/Converters/GeoJsonConverterFactory.cs#L14-L19)", but you can configure it to look for a different attribute name by using an [overload](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/106db44029ca67e207e4c88400537f49c005aa7c/src/NetTopologySuite.IO.GeoJSON4STJ/Converters/GeoJsonConverterFactory.cs#L69-L78) of the `GeoJsonConverterFactory` constructor that accepts it.

**Comment by airbreather** [comment]
Also, I would advise sticking with just one GeoJSON library or the other.  Each one should have a way for you to do everything you need; the only good reason I can think of for using both is if some of the libraries you use are only compatible with `Newtonsoft.Json`, and others are only compatible with `System.Text.Json`.
