### ISSUE TITLE
Custom formatting value when writing coordinates

### ISSUE THREAD

**Issue by bstordrup** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#80]
I have a GeoJson object that I would like to serialize to json file. I would like to have the json formatted using Formatting.Indented in general, but for Coordinates property, I would like to use Formatting.None. To produce the following output, where coordinates are written on oly one line:

  "Type": "FeatureCollection",
  "TotalFeatures": 9260,
  "Features": [
    {
      "Type": "Feature",
      "Geometry": {
        "Type": "Polygon",
        "Coordinates":[[[8.044133769386885,54.53800851905701],[8.045679115766974,54.538020720598645],[8.045658148516951,54.538919306798284],[8.04411276819687,54.538907104854104],[8.044133769386885,54.53800851905701]]]
      }
    },
    {
      "Type": "Feature",
      "Geometry": {
        "Type": "Polygon",
        "Coordinates":[[[8.045679115766974,54.538020720598645],[8.047224463302477,54.53803290240178],[8.047203529992544,54.53893148900329],[8.045658148516951,54.538919306798284],[8.045679115766974,54.538020720598645]]]
      }
    },

**Comment by bstordrup** [comment]
Created a pull request #81 to implement this

**Comment by bstordrup** [comment]
My pull request #81 has been merged. When will a new release of the package happen?

**Comment by FObermaier** [comment]
Closed with #81 (61bd5badca980f0af12e44d6a68f723ebe5ef7b0)
