### ISSUE TITLE
Array to FeatureCollection support

### ISSUE THREAD

**Issue by oshawa-connection** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#86]
First off, thanks very much for making this library🙂

When I try to serialise a single feature with a geometry, it works great. However, when I try to serialise a list or array of features, I just get an array of serialised features rather than a feature collection, e.g.
```csharp
            var points = await db.points.ToListAsync();
            //Here, I would need to convert the list/ array to a FeatureCollection.
            return Json(points);
```
returns
```
[{"id":1,"geom":{"type":"Point","coordinates":[1,2]},"someproperty":"somevalue"},{"id":2,"geom":{"type":"Point","coordinates":[1,2]},"someproperty":"somevalue"}]
```
rather than
```
{"type":"FeatureCollection","bbox": ...,"features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[1,2]},"properties":{"id":1,"someproperty":"somevalue"}...}
```
I know that I can convert to a FeatureCollection and serialise that, but its an extra step to take. Is this just a case of my misconfiguration or is this feature not supported yet?

Would you accept a PR for this? I would be happy to look into this if you think its possible and a sensible feature.

**Comment by DGuidi** [comment]
> I know that I can convert to a FeatureCollection

This is the way, at least for me. 
A json with a list of features (like the first one you posted) should be deserialized as a list of features, and not as a different kind of object. As you mentioned, you can explicitely build a `FeatureCollection `and achieve the results you need.
My2Cents, but I'd like to receive others' feedback

**Comment by oshawa-connection** [comment]
Ciao!

I think I must have been sleep deprived when I made this issue. When I read it again, I wonder why I thought any collection should be converted to a `FeatureCollection` without the user explicitly wanting it. Closing
