### ISSUE TITLE
Problem Serializing non-Feature based IFeature s inside a FeatureCollection using NTS.IO.GeoJSON

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#88]
[This question on stackoverflow](https://stackoverflow.com/questions/69013006/serializing-featurecollection-geojson-in-net-core) revealed that there is an issue with serializing `IFeature` implementing classes that are 
* part of a  `FeatureCollection`, 
* not derived from `Feature`

The issue is, that `FeatureCollectionConverter` attempts to copy the features to a `Feature[]`. The features should be copied to a `IFeature[]`:
https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/2019c648aa726441cf89ed45cc2ab4b305de3acf/src/NetTopologySuite.IO.GeoJSON/Converters/FeatureCollectionConverter.cs#L45-L48

**Comment by DGuidi** [comment]
@FObermaier  this issue can be closed, right?

**Comment by FObermaier** [comment]
Fixed with 13fab6fa0ef2ae6d12f763b5ae616f5b7e83cfac
