### ISSUE TITLE
GeometryArrayConverter Fails To Deserialize Enumerable<Polygon>

### ISSUE THREAD

**Issue by mymatthew** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#89]
I found some issues in the GeometryArrayConverter that was resulting in an exception whenever it attempted to deserialze an Enumerable of Polygons.

The first issue stems around a reader.Read() in GeometryArrayConverter.cs that happens prematurely, which results in the generic exception.

The second issue stems in a "support gap". The ReadJson method in GeometryArrayConverter.cs ALWAYS returns a list of Geometry. In my situation the serializer was expecting an Enumerable of Polygons. The mismatched data types generates an error.

I addressed both issues and created a PR: https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/pull/90

**Comment by DGuidi** [comment]
closed with #90
