### ISSUE TITLE
Error on GeoJsonReader because referencing wrong version of Newtonsoft

### ISSUE THREAD

**Issue by MikeLeicester** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#9]
From a clean install of version 1.14.0 
though same issur occurs with V1.15.0-pre063
you get the following error when calling GeoJsonReader.Read
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
  Source=NetTopologySuite.IO.GeoJSON
  StackTrace:
   at NetTopologySuite.IO.GeoJsonReader.Read[TObject](String json)

as its only installed 3.5.8

updating to version 11.0.2 (latest stable) of newtonsoft throws  error @ Creation of a GeoJsonReader
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
  Source=NetTopologySuite.IO.GeoJSON
  StackTrace:
   at NetTopologySuite.IO.GeoJsonReader..ctor()

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

manually forcing the version to 9.0.1 fixes

**Comment by FObermaier** [comment]
A quick test with the current nuget package does not show this behaviour.
