### ISSUE TITLE
Reduce number of points when serializing ?

### ISSUE THREAD

**Issue by Ombrelin** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#91]
Hello,

is it possible to reduce the numebr of GeoJSON points generated when serializing a given geometry ?

Thanks in advance

**Comment by FObermaier** [comment]
To reduce/simplify the geometries you can use
* [`DouglasPeuckerSimplifier`](https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/src/NetTopologySuite/Simplify/VWSimplifier.cs)
* [`VWSimplifier`](https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/src/NetTopologySuite/Simplify/VWSimplifier.cs)

prior to serializing your geometries.
