### ISSUE TITLE
a geometry has z has missing

### ISSUE THREAD

**Issue by liugt34** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#93]
The orgin geometry is 
MULTILINESTRING Z ((105.9678044888003 26.3126820704801 10,106.25675603648882 26.33994165045072 20,106.25675603648882 26.241807162556498 20,106.71471697999519 26.35629739843309 30))

and the result  the z value missed

**Comment by DGuidi** [comment]
how do you build the geometry? can you post the code used to reproduce the error, and not only the WKT string?

**Comment by liugt34** [comment]
use this
 var serializer = GeoJsonSerializer.Create(GeometryFactory.Default, 3);
