### ISSUE TITLE
interpolated property

### ISSUE THREAD

**Issue by GioviQ** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#94]
Using https://docs.mapbox.com/api/search/geocoding/#forward-geocoding

I have GeoJSON with

`"geometry": {
        "type": "Point",
        "coordinates": [ -117.267131, 32.959175 ],
        "interpolated": true
      }`

Parsing "interpolated" gives exception.

"interpolated" seems not a proper GeoJSON property.

Am I right?

**Comment by DGuidi** [comment]
GeoJSON [feature object](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2) doesn't allow "interpolated" property as a "root" property, so I assume that the map 
box return message is not a valid GeoJSON?

**Comment by GioviQ** [comment]
Root property? The above is only the Json part to present the issue, not the full response.
To MapBox interpolated is a property of Point and maybe all other geometries.

**Comment by DGuidi** [comment]
What I meant is that a feature object in GeoJSON should have  "geometry", "properties", "type" and "id" properties only. So the "interpolated" property is a bit unexpected at this level.

**Comment by DGuidi** [comment]
I should admit that [foreign members](https://datatracker.ietf.org/doc/html/rfc7946#section-6.1) are allowed, so the geojson code should be deserialized.

**Comment by GioviQ** [comment]
If you go in https://docs.mapbox.com/playground/geocoding/?search_text=1043%20Coast%20Blvd%20S%2CLa%20Jolla%2CCA%2C92037&types=place%2Cpostcode%2Caddress

look for feature[3] in the response tab

**Comment by GioviQ** [comment]
To discover the error I had to debug this repository because the exception is not clear.
Newtonsoft: Expected token '}' not found
Stj: StjGeometryConverter read too much or not enough

**Comment by DGuidi** [comment]
So the problem lies in both `NetTopologySuite.IO.GeoJSON4` and `NetTopologySuite.IO.GeoJSON4STJ` libraries.
I discovered the problem, basically (and for `NetTopologySuite.IO.GeoJSON4`) the serializer [is not advanced](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/develop/src/NetTopologySuite.IO.GeoJSON/Converters/GeometryConverter.cs#L455) after that the additional properties is read.
Working on it.
