### ISSUE TITLE
Exception null coordinates inner polygon geometry

### ISSUE THREAD

**Issue by vgallego** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#96]
I updated to the last version, but I still breaks the reading if I receive null coordinates inside the geometry. 

Here I put an example of feature that is not working for me:
```json
{
    "type": "Feature",
    "id": "955r48cb-129f-44ce-a229-cbd065a67bcf",
    "properties": {
        "name": "test",
        "updated": "",
        "altitude": 2657,
        "longitude": -116.425598,
        "latitude": 33.523399
    },
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    null
                ]
            ]
        ]
    }
}
```
I am using ver. 2.0.4

**Comment by DGuidi** [comment]
this is not a valid GeoJSON file, at least as far as I know. what do you expect as result from this input?

**Comment by vgallego** [comment]
I know that is not a geosjon, I paste a part of feature collection, the main problem is that I request a geojson that returns some geometries (polygon type) with null coordinates, and when I try to read it, I can't deserialize it... 
Can I remove the nodes that contains null values for each empty polygon?

**Comment by FObermaier** [comment]
@DGuidi is right, there was a `,` (comma) after the `latitude` property which made the snipplet invalid. I removed it.

**Comment by DGuidi** [comment]
@FObermaier I think the comma is accepted by the "legacy" geoJSON parser, but the error is related to the missing coordinate values that are actually not handled. See test case I added. Not sure how input like this should be handled: should an empty geometry returned in any case?

**Comment by FObermaier** [comment]
Jsonlint says it not valid.

**Comment by vgallego** [comment]
I got an example of this schema collection, I know as geojson, it is not valid, but some elements of the collection come like this sometimes, the geometry is not null, but its internal coordinates are. I need to know if nts discards these null values:

{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "id":"d2673d31-6adc-4ea2-84c0-019202b6c415",
         "properties":{
            "name":"FeatureName2",
            "longitude":-118.2276,
            "latitude":41.980499,
            "state":"ID"
         },
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     null
                  ]
               ]
            ]
         }
      },
      {
         "type":"Feature",
         "id":"d2673d31-6adc-4ea2-84c0-019202b6c415",
         "properties":{
            "name":"FeatureName2",
            "longitude":-116.6576,
            "latitude":42.980499,
            "state":"ID"
         },
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     null
                  ]
               ]
            ]
         }
      }
   ]
}

**Comment by DGuidi** [comment]
the code you posted is [valid json](https://jsonlint.com/) but [invalid geojson](https://geojsonlint.com/)
![image](https://user-images.githubusercontent.com/216627/151507261-a293408f-8e84-4a8f-b01e-9778f2d4e5a7.png)

```
{
	"type": "FeatureCollection",
	"features": [{
		"type": "Feature",
		"id": "d2673d31-6adc-4ea2-84c0-019202b6c415",
		"properties": {
			"name": "FeatureName2",
			"longitude": -118.2276,
			"latitude": 41.980499,
			"state": "ID"
		},
		"geometry": {
			"type": "Polygon",
			"coordinates": [
				[
					[
						null
					]
				]
			]
		}
	}, {
		"type": "Feature",
		"id": "d2673d31-6adc-4ea2-84c0-019202b6c415",
		"properties": {
			"name": "FeatureName2",
			"longitude": -116.6576,
			"latitude": 42.980499,
			"state": "ID"
		},
		"geometry": {
			"type": "Polygon",
			"coordinates": [
				[
					[
						null
					]
				]
			]
		}
	}]
}
```

**Comment by DGuidi** [comment]
This looks a valid geojson of an empty polygon, that is not serialized by GeoJSON libraries
```
{
	"type": "Feature",
	"id": "955r48cb-129f-44ce-a229-cbd065a67bcf",
	"properties": {
		"name": "test",
		"updated": "",
		"altitude": 2657,
		"longitude": -116.425598,
		"latitude": 33.523399
	},
	"geometry": {
		"type": "Polygon",
		"coordinates": []
	}
}
```

**Comment by DGuidi** [comment]
>  I need to know if nts discards these null values

@vgallego the simple answer is "no": NTS as a library should handle (in my opinion) only valid data, and should throws error in case of invalid input.
